[package]
name = "budget-manager-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.29"
console = "0.15"
tui = "0.19"
crossterm = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
warp = "0.3"
